# Generated by Django 5.0.2 on 2024-05-07 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0004_remove_insumo_aprovado_remove_insumo_documento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='empresa_nome',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='telefone',
        ),
    ]
