# Generated by Django 5.0.2 on 2024-05-07 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0006_preco_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='djangoProject.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preco',
            name='data_cotacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preco',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
