# Generated by Django 5.0.2 on 2024-05-07 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0008_preco_nome_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preco',
            name='nome_empresa',
        ),
    ]
