# Generated by Django 5.0.2 on 2024-06-02 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0015_mapa_title_delete_insumopendente'),
    ]

