# Generated by Django 5.0.2 on 2024-05-28 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapadecotacao', '0011_delete_insumopendente'),
    ]


