# Generated by Django 5.0.2 on 2024-05-29 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapadecotacao', '0013_delete_insumopendente'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivoanexado',
            name='preco',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_anexados', to='mapadecotacao.preco'),
            preserve_default=False,
        ),
    ]
