# Generated by Django 5.1.1 on 2024-11-25 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapadecotacao', '0019_customuser_name_customuser_photo_customuser_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='empresa',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='mapadecotacao.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pasta',
            name='empresa',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='mapadecotacao.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pasta',
            name='pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapadecotacao.pasta'),
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapadecotacao.orcamento')),
            ],
        ),
        migrations.AddField(
            model_name='composicaosicro3',
            name='etapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapadecotacao.etapa'),
        ),
        migrations.AddField(
            model_name='composicaosinapi',
            name='etapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapadecotacao.etapa'),
        ),
        migrations.CreateModel(
            name='Subetapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapadecotacao.etapa')),
            ],
        ),
        migrations.AddField(
            model_name='composicaosicro3',
            name='subetapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapadecotacao.subetapa'),
        ),
        migrations.AddField(
            model_name='composicaosinapi',
            name='subetapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapadecotacao.subetapa'),
        ),
    ]
