# Generated by Django 5.1.1 on 2024-11-25 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapadecotacao', '0020_orcamento_empresa_pasta_empresa_pasta_pai_etapa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasta',
            name='pai',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='pasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='mapadecotacao.pasta'),
        ),
        migrations.AddField(
            model_name='pasta',
            name='parent_pasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subpastas', to='mapadecotacao.pasta'),
        ),
    ]
