# Generated by Django 5.1.1 on 2024-11-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapadecotacao', '0021_remove_pasta_pai_orcamento_pasta_pasta_parent_pasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
