# Generated by Django 5.1.1 on 2024-11-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapadecotacao', '0022_alter_orcamento_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
