# Generated by Django 5.1.1 on 2024-11-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapadecotacao', '0023_etapa_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapa',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='subetapa',
            name='descricao',
        ),
        migrations.AddField(
            model_name='etapa',
            name='nivel',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subetapa',
            name='nivel',
            field=models.IntegerField(default=1.1),
        ),
    ]
