# Generated by Django 5.1.1 on 2025-01-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapadecotacao', '0024_remove_etapa_descricao_remove_subetapa_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='tipo',
            field=models.CharField(choices=[('SINAPI', 'SINAPI'), ('SICRO', 'SICRO'), ('PROPRIO', 'Próprio')], default='PROPRIO', max_length=10),
        ),
    ]
