# Generated by Django 5.1.1 on 2025-01-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapadecotacao', '0025_insumo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='preco',
            name='preco_desonerado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='preco',
            name='preco_nao_desonerado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
