# Generated by Django 5.1.1 on 2025-01-14 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapadecotacao', '0026_preco_preco_desonerado_preco_preco_nao_desonerado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapadecotacao.empresa'),
        ),
    ]
