# Generated by Django 5.1.1 on 2025-01-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapadecotacao', '0027_alter_insumo_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SINAPI', 'SINAPI'), ('PROPRIO', 'Próprio'), ('SICRO', 'SICRO')], default='SINAPI', max_length=10)),
                ('descricao_classe', models.CharField(max_length=255)),
                ('sigla_classe', models.CharField(max_length=50)),
                ('codigo_composicao', models.CharField(max_length=50, unique=True)),
                ('descricao_composicao', models.TextField()),
                ('unidade_medida', models.CharField(max_length=50)),
                ('custo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_item', models.CharField(max_length=50)),
                ('codigo_item', models.CharField(max_length=50)),
                ('descricao_item', models.CharField(max_length=255)),
                ('unidade_item', models.CharField(max_length=50)),
                ('coeficiente', models.DecimalField(decimal_places=4, max_digits=10)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo_mao_obra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percent_mao_obra', models.DecimalField(decimal_places=2, max_digits=5)),
                ('custo_material', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percent_material', models.DecimalField(decimal_places=2, max_digits=5)),
                ('custo_equipamento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percent_equipamento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('custo_servicos_terceiros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percent_servicos_terceiros', models.DecimalField(decimal_places=2, max_digits=5)),
                ('custo_outros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percent_outros', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
