# Generated by Django 5.1.1 on 2025-01-15 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapadecotacao', '0028_composicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='composicao',
            name='custo_total_item',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='composicao',
            name='data_cotacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preco',
            name='composicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='precos', to='mapadecotacao.composicao'),
        ),
        migrations.AlterField(
            model_name='preco',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='precos', to='mapadecotacao.insumo'),
        ),
    ]
