# Generated by Django 5.1.1 on 2025-01-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapadecotacao', '0030_alter_composicao_custo_equipamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preco',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='preco',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='preco',
            name='razao_social',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='preco',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='preco',
            name='vendedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
