# Generated by Django 5.1.1 on 2025-01-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapadecotacao', '0031_alter_preco_cnpj_alter_preco_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composicao',
            name='coeficiente',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='composicao',
            name='preco_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
