# Generated by Django 5.1.1 on 2025-01-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapadecotacao', '0032_alter_composicao_coeficiente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='composicao',
            name='composicoes_auxiliares',
            field=models.ManyToManyField(blank=True, related_name='composicoes_principais', to='mapadecotacao.composicao'),
        ),
        migrations.AddField(
            model_name='composicao',
            name='insumos',
            field=models.ManyToManyField(blank=True, related_name='composicoes', to='mapadecotacao.insumo'),
        ),
    ]
