# Generated by Django 5.1.1 on 2025-01-15 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapadecotacao', '0033_composicao_composicoes_auxiliares_composicao_insumos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composicao',
            name='codigo_item',
        ),
        migrations.RemoveField(
            model_name='composicao',
            name='coeficiente',
        ),
        migrations.RemoveField(
            model_name='composicao',
            name='custo_equipamento',
        ),
        migrations.RemoveField(
            model_name='composicao',
            name='custo_mao_obra',
        ),
        migrations.RemoveField(
            model_name='composicao',
            name='custo_material',
        ),
        migrations.RemoveField(
            model_name='composicao',
            name='custo_outros',
        ),
        migrations.RemoveField(
            model_name='composicao',
            name='custo_servicos_terceiros',
        ),
        migrations.RemoveField(
            model_name='composicao',
            name='custo_total_item',
        ),
        migrations.RemoveField(
            model_name='composicao',
            name='descricao_item',
        ),
        migrations.RemoveField(
            model_name='composicao',
            name='percent_equipamento',
        ),
        migrations.RemoveField(
            model_name='composicao',
            name='percent_mao_obra',
        ),
        migrations.RemoveField(
            model_name='composicao',
            name='percent_material',
        ),
        migrations.RemoveField(
            model_name='composicao',
            name='percent_outros',
        ),
        migrations.RemoveField(
            model_name='composicao',
            name='percent_servicos_terceiros',
        ),
        migrations.RemoveField(
            model_name='composicao',
            name='preco_unitario',
        ),
        migrations.RemoveField(
            model_name='composicao',
            name='tipo_item',
        ),
        migrations.RemoveField(
            model_name='composicao',
            name='unidade_item',
        ),
        migrations.CreateModel(
            name='Coeficiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coeficiente', models.DecimalField(decimal_places=4, max_digits=12)),
                ('composicao_mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coeficientes_mae', to='mapadecotacao.composicao')),
            ],
        ),
        migrations.CreateModel(
            name='ComposicaoAuxiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SINAPI', 'SINAPI'), ('PROPRIO', 'Próprio'), ('SICRO', 'SICRO')], default='SINAPI', max_length=10)),
                ('codigo_composicao_auxiliar', models.CharField(max_length=100)),
                ('descricao_composicao_auxiliar', models.TextField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('custo_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('coeficientes', models.ManyToManyField(related_name='composicoes_auxiliares_coefs', to='mapadecotacao.coeficiente')),
                ('composicao_mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composicoes_auxiliares_mae', to='mapadecotacao.composicao')),
            ],
        ),
        migrations.AddField(
            model_name='coeficiente',
            name='composicao_auxiliar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coeficientes_auxiliar', to='mapadecotacao.composicaoauxiliar'),
        ),
        migrations.AlterField(
            model_name='composicao',
            name='composicoes_auxiliares',
            field=models.ManyToManyField(blank=True, related_name='composicoes_mãe', to='mapadecotacao.composicaoauxiliar'),
        ),
    ]
