# Generated by Django 5.1.1 on 2025-01-17 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapadecotacao', '0034_remove_composicao_codigo_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preco',
            name='composicao',
        ),
    ]
