# Generated by Django 5.1.1 on 2025-01-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapadecotacao', '0035_remove_preco_composicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composicao',
            name='custo_total',
        ),
        migrations.AddField(
            model_name='composicao',
            name='preco_desonerado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='composicao',
            name='preco_nao_desonerado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
