# Generated by Django 5.1.1 on 2025-01-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapadecotacao', '0036_remove_composicao_custo_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composicaoauxiliar',
            name='custo_total',
        ),
        migrations.RemoveField(
            model_name='composicaoauxiliar',
            name='preco_unitario',
        ),
        migrations.AddField(
            model_name='composicaoauxiliar',
            name='custo_total_desonerado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='composicaoauxiliar',
            name='custo_total_nao_desonerado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='composicaoauxiliar',
            name='preco_desonerado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='composicaoauxiliar',
            name='preco_nao_desonerado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
