# Generated by Django 5.1.1 on 2025-01-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapadecotacao', '0037_remove_composicaoauxiliar_custo_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='composicaoauxiliar',
            name='unidade_medida',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
