# Generated by Django 5.1.1 on 2025-01-20 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapadecotacao', '0038_composicaoauxiliar_unidade_medida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composicaoauxiliar',
            name='custo_total_desonerado',
        ),
        migrations.RemoveField(
            model_name='composicaoauxiliar',
            name='custo_total_nao_desonerado',
        ),
    ]
