# Generated by Django 5.1.1 on 2025-01-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapadecotacao', '0039_remove_composicaoauxiliar_custo_total_desonerado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coeficiente',
            name='coeficiente',
            field=models.DecimalField(decimal_places=10, max_digits=50),
        ),
    ]
