# Generated by Django 5.1.1 on 2025-01-20 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapadecotacao', '0040_alter_coeficiente_coeficiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='coeficiente',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coeficientes', to='mapadecotacao.insumo'),
        ),
    ]
