# Generated by Django 5.1.1 on 2025-01-20 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapadecotacao', '0041_coeficiente_insumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coeficiente',
            name='composicao_auxiliar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coeficientes_auxiliar', to='mapadecotacao.composicaoauxiliar'),
        ),
    ]
