# Generated by Django 5.1.1 on 2025-01-24 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapadecotacao', '0042_alter_coeficiente_composicao_auxiliar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapa',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='subetapa',
            name='nivel',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='bdi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=512)),
                ('composicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapadecotacao.composicao')),
                ('etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapadecotacao.etapa')),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapadecotacao.insumo')),
                ('subetapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapadecotacao.subetapa')),
            ],
        ),
    ]
