# Generated by Django 5.1.1 on 2025-01-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapadecotacao', '0043_remove_etapa_nivel_remove_orcamento_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivel',
            name='quantidade',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
