# Generated by Django 5.1.1 on 2025-01-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapadecotacao', '0044_nivel_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivel',
            name='quantidade',
            field=models.DecimalField(blank=True, decimal_places=10, default=1, max_digits=20, null=True),
        ),
    ]
