# Generated by Django 5.1.1 on 2025-02-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapadecotacao', '0045_alter_nivel_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='desonerado',
            field=models.BooleanField(default=False),
        ),
    ]
