# Generated by Django 5.1.1 on 2025-02-07 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapadecotacao', '0046_orcamento_desonerado'),
    ]

    operations = [
        migrations.AddField(
            model_name='composicao',
            name='empresa',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapadecotacao.empresa'),
        ),
    ]
