# Generated by Django 5.0.2 on 2024-05-29 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapadecotacao', '0012_arquivoanexado_preco'),
    ]


