# Generated by Django 5.1 on 2024-08-09 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapadecotacao', '0016_delete_insumopendente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InsumoPendente',
        ),
    ]
